name: daemon

services:
  chat:
    build:
      context: .
      dockerfile: Chat.Dockerfile
    restart: on-failure
    ports:
      - "3000:3000" # hono server
      - "5173:5173" # sveltekit dev server
    networks:
      - daemon-network
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - daemon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    neo4j:
      image: neo4j:latest
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - neo4j_data:/data
      environment:
        - NEO4J_AUTH=neo4j/lightrag
      healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s

networks:
  daemon-network:
    driver: bridge

volumes:
  postgres-data:
  neo4j_data:
