name: daemon

services:
  chat:
    build:
      context: .
      dockerfile: Chat.Dockerfile
    restart: on-failure
    ports:
      - "3000:3000" # hono server
      - "5173:5173" # sveltekit dev server
    networks:
      - daemon-network
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - daemon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  daemon-network:
    driver: bridge

volumes:
  postgres-data:
